# Общие настройки
line-length = 88
indent-width = 4

# Исключения
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "build",
    "dist",
    "migrations",  # Добавлено для Alembic
    "alembic",     # Добавлено для миграций
]

# Настройки линтинга
[lint]
select = [
    "E",   # Ошибки pycodestyle
    "W",   # Предупреждения pycodestyle
    "F",   # Pyflakes
    "I",   # Isort (сортировка импортов)
    "B",   # flake8-bugbear (умные проверки)
    "Q",   # flake8-quotes (кавычки)
    "SIM", # flake8-simplify (упрощение кода)
    "RUF", # Специфичные для Ruff правила
]

ignore = [
    "E501",  # Длина строки (уже контролируется line-length)
    "F401",  # Неиспользуемые импорты (может мешать в __init__.py)
    "B008",  # Мутирующие аргументы по умолчанию (иногда нужно в FastAPI)
    "A003",  # Переопределение встроенных имен (может быть оправдано)
]

# Специальные исключения для тестов
[lint.per-file-ignores]
"**/tests/*.py" = ["S101"]  # Разрешить assert в тестах
"**/migrations/*.py" = ["E501", "F401"]  # Игнорировать в миграциях

# Настройки форматирования
[format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

# Дополнительно для FastAPI
[lint.isort]
known-first-party = ["fastapi_project"]  # Ваше название пакета
required-imports = ["from __future__ import annotations"]