# Общие настройки
line-length = 88
indent-width = 4
fix = true
# Исключения
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "build",
    "dist",
    ".env",
    "migrations"
]

# Настройки линтинга
[lint]
select = [
    "E",   # Ошибки pycodestyle
    "W",   # Предупреждения pycodestyle
    "F",   # Pyflakes
    "I",   # Isort (сортировка импортов)
    "B",   # flake8-bugbear (умные проверки)
    "Q",   # flake8-quotes (кавычки)
    "SIM", # flake8-simplify (упрощение кода)
    "RUF", # Специфичные для Ruff правила
]

ignore = [
    "E501",  # Длина строки (уже контролируется line-length)
    "F401",  # Неиспользуемые импорты (может мешать в __init__.py)
    "B008",  # Мутирующие аргументы по умолчанию (иногда нужно в FastAPI)
    "A003",  # Переопределение встроенных имен (может быть оправдано)
    "RUF001",  # Неиспользуемые импорты с кириллицей
    "RUF002",  # Неиспользуемые переменные с кириллицей
    "RUF003",  # Неиспользуемые аргументы функций с кириллицей
    "RUF004",  # Неиспользуемые исключения с кириллицей
]

# Специальные исключения для тестов
[lint.per-file-ignores]
"parcels/tests/*.py" = ["S101"]  # Разрешить assert в тестах
"parcels/migrations/*.py" = ["E501", "F401"]  # Игнорировать в миграциях

# Настройки форматирования
[format]
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = false

