# Generated by Django 5.2 on 2025-04-15 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField(help_text='Вес в кг')),
                ('value', models.FloatField(help_text='Стоимость в USD')),
                ('delivery_cost', models.FloatField(blank=True, help_text='Стоимость доставки в RUB', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcels.parceltype')),
            ],
        ),
    ]
