# Generated by Django 5.2 on 2025-04-15 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='value',
            new_name='content_value',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='type',
            new_name='parcel_type',
        ),
    ]
