# Generated by Django 5.2 on 2025-04-15 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0002_rename_value_parcel_content_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parcel',
            old_name='parcel_type',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='parcel',
            old_name='content_value',
            new_name='value',
        ),
    ]
